#!/usr/bin/env bash

export CONTECO_LABEL="external.filebeat - ContEco"
export CONTECO_DESCRIPTION="ElasticSearch Filebeat image with ContEco external prerequisites installed."

export CONTECO_TYPE="external"
export CONTECO_NAME="filebeat"
export CONTECO_TAG="7.1.1"

export CONTECO_BASE="docker.elastic.co/beats/filebeat:7.1.1"
export CONTECO_BUILD="external-mapped"
