#!/usr/bin/env bash

export CONTECO_LABEL="External ElasticSearch Filebeat image"
export CONTECO_DESCRIPTION="Import of external ElasticSearch Filebeat image into the ContEco ecosystem."

export CONTECO_TYPE="external"
export CONTECO_NAME="filebeat"
export CONTECO_TAG="7.1.1"

export CONTECO_BASE="docker.elastic.co/beats/filebeat:7.1.1"
export CONTECO_BUILD="external-mapped"
